on: [push]

jobs:
  build:
  name: Hello world
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: nginx installation
    run: |
      sudo apt install nginx
      sudo systemctl status nginx
