on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: nginx installation
      run: |
        if nginx -v; then
          echo nginx already installed
          sudo systemctl start nginx
          sudo systemctl status nginx
        else
          sudo apt install nginx
          sudo systemctl status nginx
        fi
