on:
  push:
    paths:
      - webapp/**

jobs:
  build:
    runs-on: Windows
    steps:
    - uses: actions/checkout@v2
    
    - name: Host website on IIS
      run: |
        Remove-Item -Path "C:\inetpub\wwwroot\*" -Recurse -Force
        Copy-Item -Path "webapp\*" -Destination "C:\inetpub\wwwroot" -Recurse -Force
